services:
  - type: web
    name: lucrumia-scraper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    schedule:
      type: cron
      cron: "*/5 * * * *"